[package]
name = "quadcopter_simple_exp"
version = "0.1.0"
edition = "2021"

[dependencies]
rtreach = { path = "../../rtreach" }
quadcopter = { path = "../../quadcopter" }
tract = "0.21.7"
tract-onnx = "0.21.7"