[package]
name = "bicycle_nbd_exp"
version = "0.1.0"
edition = "2021"

[dependencies]
rtreach = { path = "../../rtreach" }
bicycle = { path = "../../bicycle" }
tract = "0.21.7"
tract-onnx = "0.21.7"
csv = "1.3.0"
pbr = "1.1.1"
lazy_static = "1.5.0"